### ISSUE TITLE
After V3 upgrade i'm getting Error: buffer_from_1 is not defined

### ISSUE THREAD

**Issue by Bnaya** [TooTallNate/node-data-uri-to-buffer#13]
I'm not sure what's broken in the transpiled  code, or i have something wrong with my node setup that breaks it

that's from the lib's transpiled code:
```
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
const buffer_from_1 = __importDefault(require("buffer-from"));
```
seems like regular typescript emit with modules interop

**Comment by TooTallNate** [comment]
Please try [`v3.0.1`](https://github.com/TooTallNate/node-data-uri-to-buffer/releases/tag/3.0.1). The `buffer-from` dependency has been removed.
