### ISSUE TITLE
remove bufferFrom

### ISSUE THREAD

**Issue by jimmywarting** [TooTallNate/node-data-uri-to-buffer#14]
would you be keen on removing bufferFrom dependency? Buffer.from have been available for a while now. Can make a PR if you like.

**Comment by TooTallNate** [comment]
Ya I'd be fine with that.

**Comment by TooTallNate** [comment]
Please try [`v3.0.1`](https://github.com/TooTallNate/node-data-uri-to-buffer/releases/tag/3.0.1). The `buffer-from` dependency has been removed.
