### ISSUE TITLE
Parses meta with useless semicolons incorrectly

### ISSUE THREAD

**Issue by melusc** [TooTallNate/node-data-uri-to-buffer#17]
With a datauri like `data:text/plain;,text`, and the library parsing it, it results in `.typeFull` equalling `text/plain;;charset=US-ASCII` (instead of `text/plain;charset=US-ASCII`).

With a datauri like `data:;,text`, and the library parsing it, it results in `.typeFull` equalling `text/plain;` (instead of `text/plain`).

( I do think that they are valid datauris because browsers return what you'd expect, for example `data:text/html;;,<h1>Hello</h1>` showing a huge Hello )

Replacing [this line](https://github.com/TooTallNate/node-data-uri-to-buffer/blob/50595222bae70daa90bf370bdd48f981cb3e3eea/src/index.ts#L40) with `} else if(meta[i]) {` fixed it for me.

**Comment by TooTallNate** [comment]
Ya that seems like a bug. Pull request welcome!

**Comment by melusc** [comment]
If nobody does so before me, I'll make one tomorrow.
