### ISSUE TITLE
Shouldn't it throw for invalid uri's?

### ISSUE THREAD

**Issue by caub** [TooTallNate/node-data-uri-to-buffer#4]
It doesn't throw for:
```
data:image/jpeg;base64,R75B--ADs=
data:image/jpeg;b4,R75B--ADs=
data:i@@jg;base64,R75B--ADs=
data:im...;..Ds=,
```
But validating data-uri can be done separately though

**Comment by TooTallNate** [comment]
Well Node.js `new Buffer('R75B--ADs=', 'base64')` doesn't seem to complain. Im inclined to just leave it as is to be honest.

**Comment by caub** [comment]
ok, note we should be using `Buffer.from('R75B--ADs=', 'base64')`
