### ISSUE TITLE
v1.1.0 dependency breaks npm install

### ISSUE THREAD

**Issue by irnnr** [TooTallNate/node-data-uri-to-buffer#5]
Trying to do an `npm i` causes it to fail when "data-uri-to-buffer" is in the dependency tree.  
It chokes on requiring "types/node" 

```
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'types/node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'data-uri-to-buffer'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Darwin 16.6.0
npm ERR! command "/Users/ingo/.nvm/v0.10.37/bin/node" "/Users/ingo/.nvm/v0.10.37/bin/npm" "i" "--production"
npm ERR! cwd /Users/ingo/august/august-rest-api
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0
```
<img width="649" alt="screen shot 2017-07-18 at 11 45 55 am" src="https://user-images.githubusercontent.com/320915/28334107-f0130ab2-6bae-11e7-9d53-c397850b7875.png">

**Comment by TooTallNate** [comment]
You're using rather old versions of both Node.js and npm. You should upgrade. The specific issue here is that your copy of npm does not support [scoped modules](https://docs.npmjs.com/misc/scope). You'll need npm@2 or newer for that to work.

**Comment by irnnr** [comment]
This is the commit which caused this: https://github.com/TooTallNate/node-data-uri-to-buffer/commit/1ccf6d0d599b005e8a6ce422d7c7522eb677b01d

With old Node.js/npm versions you cannot use scoped dependencies. 
Node.js v0.10 (in our case) ships with npm v1.4; scoped dependencies are supported with npm v2+

https://docs.npmjs.com/misc/scope

**Comment by irnnr** [comment]
If you decide to increase the version needed to use your package you should increase the major version of data-uri-to-buffer. You just bumped the minor version, but should have gone to v2.0.0, thus breaking dependents.

You could also specify the "engines" property in package.json

**Comment by TooTallNate** [comment]
Ok see v1.2.0 and v2.0.0.

**Comment by irnnr** [comment]
Thanks so much!  
It's not like we're not aware we're running an old Node version, but we're not done with the upgrade just yet. :)
