### ISSUE TITLE
package on npm is still with @types/node as dependencies

### ISSUE THREAD

**Issue by TotooriaHyperion** [TooTallNate/node-data-uri-to-buffer#9]
data-uri-to-buffer@2:
  version "2.0.1"
  resolved "https://registry.npm.taobao.org/data-uri-to-buffer/download/data-uri-to-buffer-2.0.1.tgz#ca8f56fe38b1fd329473e9d1b4a9afcd8ce1c045"
  integrity sha1-yo9W/jix/TKUc+nRtKmvzYzhwEU=
  dependencies:
    "@types/node" "^8.0.7"

from yarn.lock

![image](https://user-images.githubusercontent.com/16434801/58698582-19270500-83ce-11e9-9982-edc28dc3d9a4.png)
from the tgz file.

please publish a patch and set @types/node version to *

**Comment by paranoidjk** [comment]
same problem here， @TooTallNate please publish a patch

**Comment by paranoidjk** [comment]
https://github.com/TooTallNate/node-data-uri-to-buffer/commit/0845dd4775dfada34255591642cd9388aa020b54  @TooTallNate seems you already fix it, but haven't publish a new version yet

**Comment by LeviticusMB** [comment]
Please, we need a new NPM release that fixes the `@types/node` problem. It breaks our build.

**Comment by TooTallNate** [comment]
Sorry for the delay. Published [`v2.0.2`](https://github.com/TooTallNate/node-data-uri-to-buffer/releases/tag/2.0.2) to npm.
